# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-04 20:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_auto_20180504_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='access_token',
        ),
    ]
