# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-06 12:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_remove_user_access_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='vk_id',
            new_name='access_token',
        ),
    ]
