# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-07 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_auto_20180506_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.CharField(default='', max_length=100)),
                ('attachments', models.CharField(default='', max_length=1000000)),
                ('comments', models.CharField(default='', max_length=1000000)),
                ('post_id', models.CharField(default='', max_length=100)),
                ('text', models.CharField(default='', max_length=1000000)),
                ('link', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='posts',
            field=models.CharField(default='', max_length=1000000),
        ),
        migrations.AlterField(
            model_name='user',
            name='access_token',
            field=models.CharField(default='', max_length=100),
        ),
    ]
