# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-14 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_auto_20180507_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='attachments',
        ),
        migrations.AddField(
            model_name='post',
            name='message',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(default='', max_length=1000000),
        ),
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
