# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-19 23:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_remove_post_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
    ]
